/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RoutePlannerRouteImport } from './routes/route-planner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StationsRouteImport } from './routes/stations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutePlannerRoute = RoutePlannerRouteImport.update({
  id: '/route-planner',
  path: '/route-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/favorites': typeof FavoritesRoute
  '/route-planner': typeof RoutePlannerRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/favorites': typeof FavoritesRoute
  '/route-planner': typeof RoutePlannerRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/favorites': typeof FavoritesRoute
  '/route-planner': typeof RoutePlannerRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/favorites'
    | '/route-planner'
    | '/settings'
    | '/stations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/favorites'
    | '/route-planner'
    | '/settings'
    | '/stations'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/favorites'
    | '/route-planner'
    | '/settings'
    | '/stations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FavoritesRoute: typeof FavoritesRoute
  RoutePlannerRoute: typeof RoutePlannerRoute
  SettingsRoute: typeof SettingsRoute
  StationsRoute: typeof StationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-planner': {
      id: '/route-planner'
      path: '/route-planner'
      fullPath: '/route-planner'
      preLoaderRoute: typeof RoutePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  FavoritesRoute: FavoritesRoute,
  RoutePlannerRoute: RoutePlannerRoute,
  SettingsRoute: SettingsRoute,
  StationsRoute: StationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
